import '../assets/css/animate.css';
import '../assets/css/bootstrap.min.css';
// import '../assets/css/line-awesome.css';
// import '../assets/css/line-awesome-font-awesome.min.css';
// import '../assets/vendor/fontawesome-free/css/all.min.css';
// import '../assets/css/font-awesome.min.css';
import '../assets/css/jquery.mCustomScrollbar.min.css';
import '../assets/lib/slick/slick.css';
import '../assets/lib/slick/slick-theme.css';
import '../assets/css/style.css';
import '../assets/css/responsive.css';