export const INIT_DATA="INIT_DATA"
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS"
export const FETCH_DATA_FAILED="FETCH_DATA_FAILED"

export const INIT_USER_LOGIN="INIT_USER_LOGIN"
export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILED="USER_LOGIN_FAILED"

export const INIT_USER_REGISTER="INIT_USER_REGISTER"
export const USER_REGISTER_SUCCESS="USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAILED="USER_REGISTER_FAILED"

export const INIT_USER_LOGOUT="INIT_USER_LOGOUT"
export const USER_LOGOUT_SUCCESS="USER_LOGOUT_SUCCESS"
export const USER_LOGOUT_FAILED="USER_LOGOUT_FAILED"

export const PRASANG_USER_LOGIN_SUCCESS = "PRASANG_USER_LOGIN_SUCCESS"